### ISSUE TITLE
Go through Gatherer and Segment Gatherer log messages

### ISSUE THREAD

**Issue by pnuu** [pytroll/pytroll-collectors#65]
I'll be needing better defined log messages at proper levels when starting to feed the logs to Graylog. At least the messages by `gatherer.py` and `segment_gatherer.py` need to be checked and adjusted as necessary.

**Comment by gerritholl** [comment]
Example issue: if a file appears that `trollstalker` doesn't know what to do with, the only message that appears with `INFO` level is

```
[INFO: 2021-01-13 17:49:07,301: trollstalker] Couldn't extract any usefull information
```

which would be more useful if it at least contained the filename from which it couldn't extract useful information.
